### ISSUE TITLE
Link to atlas-cert-manager from the cert-manager.io website

### ISSUE THREAD

**Issue by wallrj** [nhgs64/atlas-cert-manager#6]
I found your project while searching for integrations between GlobalSign + cert-manager.

When you're ready, consider adding a link to your external issuer here:
 *  https://cert-manager.io/docs/configuration/external/#known-external-issuers

Add a paragraph explaining who maintains the project and maybe a note about maturity of the project so that people can judge whether it is ready to be used in production.

**Comment by yateeshbhardwaj94** [comment]
@wallrj Thanks for your reply with this important Information. We will raise the Pull request through [GlobalSign's repository](https://github.com/globalsign/atlas-cert-manager) to become an external issuer. We are really excited to be a part of Certmanager.

**Comment by iamantil** [comment]
@wallrj When creating the PR the repo(cert-manager/website) is comparing for the changes which not where exactly the changes needs to be done to create the pull request over cert-manager/website ?
We have the plugin repo available over GitHub.
Could you brief us about the PR procedure ?

**Comment by wallrj** [comment]
* Fork the https://github.com/cert-manager/website repo
* Create a branch called `6-atlas-issuer`.
* Add a new row to the issuers table. Like https://github.com/cert-manager/website/commit/e3fa3796d28a5ae144c873d5ba042dd2f0d09031

https://github.com/cert-manager/website/blob/2c1ddbafed86aa4a311aacb2c2bd7e21e9c4feb3/content/docs/configuration/issuers.md#L13-L14

* `git commit --signoff ...`
* `git push`
* Create a "New Pull Request": https://github.com/cert-manager/website/pulls
* Ping me for a code review :-)

**Comment by iamantil** [comment]
Hey @wallrj, I have raised the PR https://github.com/cert-manager/website/pull/1382. The PR is from my official GitHub account name PrashantGSIN. Kindly review and let us know if you need anything.

**Comment by iamantil** [comment]
Hey @wallrj, The PR got failed may due to the wrong commit.
I have run the commit git commit -m "--signed-off-by: Prashant.Antil@GlobalSign.com"
Should it be git commit -s -m "Adding GlobalSign Issuer" --author="Prashant.Antil@GlobalSign.com"
And also what about the spelling of GobalSign ? Should that be added into .spellings ?

**Comment by wallrj** [comment]
Thanks. Yes, that should work. The `-s` is the important flag. And adding GlobalSign to `.spellings` file will fix the spell check warnings. 
Please rebase your PR because I've just fixed the table formatting in https://github.com/cert-manager/website/pull/1383

**Comment by iamantil** [comment]
@wallrj, I have done it. Could you check at your end ? Let me know if that looks fine to you.

**Comment by wallrj** [comment]
I rebased it and merged it. Thanks!
